### ISSUE TITLE
Unable to build on Ubuntu (1.16.5)

### ISSUE THREAD

**Issue by ac101m** [Zodsmar/SeedSearcherStandaloneTool#89]
Ubuntu: 20.04
Kernel: 5.4.105 generic
Gradle: 6.8.3
Openjdk: 11.0.10
Minecraft: 1.16.5

Installation process:
```
# git clone <this repository>
# export JAVA_HOME=<jdk installation>
# gradle wrapper
# ./gradlew build
<errors>
```

These are the errors:
```
> Task :compileJava FAILED
/cluster/ac/projects/SeedSearcherStandaloneTool/src/main/java/sassa/util/Structures.java:21: error: incompatible types: incompatible parameter types in method reference
        STRUCTURE.put(Structure.getName(RuinedPortal.class) + "_overworld", new StructureProvider(RuinedPortal::new, MCVersion.v1_16, Dimension.OVERWORLD, 1));
                                                                                                  ^
/cluster/ac/projects/SeedSearcherStandaloneTool/src/main/java/sassa/util/Structures.java:22: error: incompatible types: incompatible parameter types in method reference
        STRUCTURE.put(Structure.getName(RuinedPortal.class) + "_nether", new StructureProvider(RuinedPortal::new, MCVersion.v1_16, Dimension.NETHER, 1));
```

Looks to me like it references some class who's type changed in minecraft 1.16.5?

Then again, I'm not a java developer and this is my first time using gradle so I could well just be doing something silly!

**Comment by ac101m** [comment]
Looks like removing those two lines allows it to build.

**Comment by ac101m** [comment]
Running with those lines commented out results in the following error:
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: kaptainwutax/noiseutils/perlin/PerlinNoiseSampler
        at kaptainwutax.biomeutils.layer.water.OceanTemperatureLayer.<init>(OceanTemperatureLayer.java:15)
        at kaptainwutax.biomeutils.source.OverworldBiomeSource.build(OverworldBiomeSource.java:188)
        at kaptainwutax.biomeutils.source.OverworldBiomeSource.<init>(OverworldBiomeSource.java:70)
        at kaptainwutax.biomeutils.source.OverworldBiomeSource.<init>(OverworldBiomeSource.java:55)
        at sassa.searcher.Searcher.getBiomeSource(Searcher.java:175)
        at sassa.searcher.BiomeSearcher.findBiome(BiomeSearcher.java:21)
        at sassa.searcher.SearchingThread.searching(SearchingThread.java:133)
        at sassa.searcher.SearchingThread.run(SearchingThread.java:51)
Caused by: java.lang.ClassNotFoundException: kaptainwutax.noiseutils.perlin.PerlinNoiseSampler
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 8 more

The UI seems to think the search is still running, but there's no CPU activity.

**Comment by smcbot** [comment]
if you change the `RuinedPortal::new` on each of those lines to `v -> new RuinedPortal(Dimension.OVERWORLD, v)` and `v -> new RuinedPortal(Dimension.NETHER, v)` respectively, it fixes the issue. It is very weird however that this bug is in the code as it seems like there is no way that it wouldn't be fatal.

**Comment by smcbot** [comment]
Go into sassa.util.structures, find lines 21 & 22, and find on both lines where it says `RuinedPortal::new`. On line 21, replace this with `v -> new RuinedPortal(Dimension.OVERWORLD, v)` and on 22 `v -> new RuinedPortal(Dimension.NETHER, v)`. Then go into build.gradle and around line 37 in the dependencies block add:
`implementation('com.github.KaptainWutax:NoiseUtils:main-SNAPSHOT')
            {
                transitive = false;
                //changing = true;
            }`
. This fixed both problems for me. It is very strange that these bugs exist, as there is no reason that they should pass basic testing.

**Comment by ac101m** [comment]
Fixing this as you have is all well and good, but it doesn't address the root cause of the issue. The dependencies in [build.gradle](https://github.com/Zodsmar/SeedSearcherStandaloneTool/blob/master/build.gradle) are for the master branch of kaptain wutax's libraries, so every time a change is made to one of those dependencies, there is a chance that it breaks this tool. 

In fairness to the author of this tool, this is how kaptainwutax suggests that his libraries be used in his readme files. Internally however, he references dependencies between his libraries by using specific commit numbers ([see here](https://github.com/KaptainWutax/BiomeUtils/blob/master/build.gradle)).

The author of this tool should adopt the same strategy if they wish to avoid similar issues in the future.

**Comment by smcbot** [comment]
Ok I will take your word for it. I just used the same syntax that was already being used in the build.gradle, but conventions are confusing.

**Comment by Zodsmar** [comment]
I brought in the merge request and going forward will try my best to avoid these issues.
